/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ASUS
 */
import sistema.*;
import javax.swing.table.DefaultTableModel;

public class ListaMiembrosIU extends javax.swing.JFrame {
    private RegistroMiembros miembros;
    private DefaultTableModel tablaMiembros;

    /**
     * Creates new form ListaMiembrosIU
     */
    public ListaMiembrosIU(RegistroMiembros miembros) {
        initComponents();

        this.miembros = miembros; 
        tablaMiembros = new DefaultTableModel();
        
        this.taListaMiembros.setModel(tablaMiembros);
        
        tablaMiembros.addColumn("ID");
        tablaMiembros.addColumn("Nombre");
        tablaMiembros.addColumn("Apellido");
        tablaMiembros.addColumn("DNI");
        tablaMiembros.addColumn("Tipo de Miembro");
        tablaMiembros.addColumn("Mesa Electoral");
        tablaMiembros.addColumn("Elección");
        rellenarDatosTabla();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaMiembros = new javax.swing.JTable();
        btnCerrarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 7, 10));

        taListaMiembros.setBackground(new java.awt.Color(125, 117, 117));
        taListaMiembros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        taListaMiembros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taListaMiembros.setForeground(new java.awt.Color(0, 0, 0));
        taListaMiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taListaMiembros.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(taListaMiembros);

        btnCerrarM.setBackground(new java.awt.Color(125, 117, 117));
        btnCerrarM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarM.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarM.setText("Cerrar");
        btnCerrarM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCerrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void rellenarDatosTabla(){
        for (int i = 0; i < miembros.longitud(); i++) {
            MiembroMesa m = miembros.iesimo(i);
            int ID = m.getId();
            String Nombre = m.getNombres();
            String Apellido = m.getApellidos();
            String DNI = String.valueOf(m.getDNI());
            String Tipo = m.getTipoMiembro();
            String ME = m.getMesa().verEnTabla();
            String E = m.getEleccion().verInfo();
            
            

            String[] fila = new String[7];
            fila[0] = String.valueOf(ID);
            fila[1] = Nombre;
            fila[2] = Apellido;
            fila[3] = DNI;
            fila[4] = Tipo;
            fila[5] = ME;
            fila[6] = E;

            this.tablaMiembros.addRow(fila);        
        }
    }
    
    private void btnCerrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaMiembrosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaMiembrosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaMiembrosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaMiembrosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroMiembros miembros2 = new RegistroMiembros();
                new ListaMiembrosIU(miembros2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taListaMiembros;
    // End of variables declaration//GEN-END:variables
}
