/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.awt.event.ActionEvent; //
import java.awt.event.ActionListener; //

import sistema.*;
public class PrincipalIU extends javax.swing.JFrame {
    private RegistroElecciones elecciones;
    private RegistroCandidatos candidatos;
    private RegistroMesas mesas;
    private RegistroMiembros miembros;
    private RegistroPartidos partidos;
    private RegistroActas actas;
    

    /**
     * Creates new form PrincipalIU
     */
    public PrincipalIU() {
        initComponents();
        partidos = new RegistroPartidos();
        miembros = new RegistroMiembros();
        mesas = new RegistroMesas();
        candidatos = new RegistroCandidatos();
        elecciones = new RegistroElecciones();
        actas = new RegistroActas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnBuscarEleccion = new javax.swing.JButton();
        btnModificarEleccion = new javax.swing.JButton();
        btnRegistrarCandidato = new javax.swing.JButton();
        btnBuscarCandidato = new javax.swing.JButton();
        btnModificarCandidato = new javax.swing.JButton();
        btnEliminarCandidato = new javax.swing.JButton();
        btnRegistrarMesa = new javax.swing.JButton();
        btnBuscarMesa = new javax.swing.JButton();
        btnModificarMesa = new javax.swing.JButton();
        btnEliminarMesa = new javax.swing.JButton();
        btnRegistrarMiembro = new javax.swing.JButton();
        btnBuscarMiembro = new javax.swing.JButton();
        btnModificarMiembro = new javax.swing.JButton();
        btnEliminarMiembro = new javax.swing.JButton();
        btnRegistrarActa = new javax.swing.JButton();
        btnBuscarActa = new javax.swing.JButton();
        btnModificarActa = new javax.swing.JButton();
        btnEliminarActa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();
        btnEliminarEleccion2 = new javax.swing.JButton();
        btnEliminarEleccion3 = new javax.swing.JButton();
        btnEliminarEleccion4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnGestionarEleccion = new javax.swing.JButton();
        btnVisualizarElecciones = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnGestionarCandidato = new javax.swing.JButton();
        btnVisualizarCandidatos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnListarPartido = new javax.swing.JButton();
        btnGestionarPartido = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnGestionarMesas = new javax.swing.JButton();
        btnVisualizarMesas = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnGestionarMiembro = new javax.swing.JButton();
        btnVisualizarMiembros = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnGestionarActa = new javax.swing.JButton();
        btnVisualizarActas = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnInformeMesa = new javax.swing.JButton();
        btnInformeEleccion = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel6);

        jButton3.setText("jButton3");
        jTabbedPane2.addTab("tab1", jButton3);

        jButton4.setText("jButton2");

        jTabbedPane4.addTab("tab1", jTabbedPane5);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane6.addTab("tab1", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jRadioButton1.setText("jRadioButton1");

        btnBuscarEleccion.setText("Buscar");

        btnModificarEleccion.setText("Modificar");

        btnRegistrarCandidato.setText("Registrar");
        btnRegistrarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCandidatoActionPerformed(evt);
            }
        });

        btnBuscarCandidato.setText("Buscar");

        btnModificarCandidato.setText("Modificar");

        btnEliminarCandidato.setText("Eliminar");

        btnRegistrarMesa.setText("Registrar");

        btnBuscarMesa.setText("Buscar");

        btnModificarMesa.setText("Modificar");

        btnEliminarMesa.setText("Eliminar");

        btnRegistrarMiembro.setText("Registrar");

        btnBuscarMiembro.setText("Buscar");

        btnModificarMiembro.setText("Modificar");

        btnEliminarMiembro.setText("Eliminar");

        btnRegistrarActa.setText("Registrar");

        btnBuscarActa.setText("Buscar");

        btnModificarActa.setText("Modificar");

        btnEliminarActa.setText("Eliminar");

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaInforme);

        btnEliminarEleccion2.setBackground(new java.awt.Color(69, 35, 35));
        btnEliminarEleccion2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarEleccion2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEleccion2.setText("Visualizar Partidos Políticos");

        btnEliminarEleccion3.setBackground(new java.awt.Color(69, 35, 35));
        btnEliminarEleccion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarEleccion3.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEleccion3.setText("Visualizar Elecciones");

        btnEliminarEleccion4.setBackground(new java.awt.Color(69, 35, 35));
        btnEliminarEleccion4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarEleccion4.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEleccion4.setText("Visualizar Elecciones");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(245, 239, 239));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(245, 239, 239));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        btnGestionarEleccion.setBackground(new java.awt.Color(69, 35, 35));
        btnGestionarEleccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarEleccion.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarEleccion.setText("Gestionar Elección");
        btnGestionarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEleccionActionPerformed(evt);
            }
        });

        btnVisualizarElecciones.setBackground(new java.awt.Color(69, 35, 35));
        btnVisualizarElecciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisualizarElecciones.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarElecciones.setText("Visualizar Elecciones");
        btnVisualizarElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarEleccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarElecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGestionarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVisualizarElecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Elección", jPanel1);

        btnGestionarCandidato.setBackground(new java.awt.Color(69, 35, 35));
        btnGestionarCandidato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarCandidato.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarCandidato.setText("Gestionar Candidato");
        btnGestionarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCandidatoActionPerformed(evt);
            }
        });

        btnVisualizarCandidatos.setBackground(new java.awt.Color(69, 35, 35));
        btnVisualizarCandidatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisualizarCandidatos.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarCandidatos.setText("Visualizar Candidatos");
        btnVisualizarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarCandidatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGestionarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVisualizarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Candidatos", jPanel2);

        btnListarPartido.setBackground(new java.awt.Color(69, 35, 35));
        btnListarPartido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListarPartido.setForeground(new java.awt.Color(255, 255, 255));
        btnListarPartido.setText("Visualizar Partidos Políticos");
        btnListarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPartidoActionPerformed(evt);
            }
        });

        btnGestionarPartido.setBackground(new java.awt.Color(69, 35, 35));
        btnGestionarPartido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarPartido.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarPartido.setText("Gestionar Partido Político");
        btnGestionarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPartidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarPartido, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(btnListarPartido, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGestionarPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnListarPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("Partido Político", jPanel3);

        btnGestionarMesas.setBackground(new java.awt.Color(69, 35, 35));
        btnGestionarMesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarMesas.setText("Gestionar Mesa Electoral");
        btnGestionarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMesasActionPerformed(evt);
            }
        });

        btnVisualizarMesas.setBackground(new java.awt.Color(69, 35, 35));
        btnVisualizarMesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisualizarMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarMesas.setText("Visualizar Mesas Electorales");
        btnVisualizarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarMesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGestionarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVisualizarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mesa Electoral", jPanel4);

        btnGestionarMiembro.setBackground(new java.awt.Color(69, 35, 35));
        btnGestionarMiembro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarMiembro.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarMiembro.setText("Gestionar Miembro de Mesa");
        btnGestionarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMiembroActionPerformed(evt);
            }
        });

        btnVisualizarMiembros.setBackground(new java.awt.Color(69, 35, 35));
        btnVisualizarMiembros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisualizarMiembros.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarMiembros.setText("Visualizar Miembros de Mesa");
        btnVisualizarMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarMiembrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVisualizarMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGestionarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVisualizarMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Miembros de Mesa", jPanel5);

        btnGestionarActa.setBackground(new java.awt.Color(69, 35, 35));
        btnGestionarActa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarActa.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarActa.setText("Gestionar Acta Electoral");
        btnGestionarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarActaActionPerformed(evt);
            }
        });

        btnVisualizarActas.setBackground(new java.awt.Color(69, 35, 35));
        btnVisualizarActas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisualizarActas.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarActas.setText("Visualizar Actas Electorales");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarActas, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarActa, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGestionarActa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVisualizarActas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acta Electoral", jPanel7);

        btnInformeMesa.setBackground(new java.awt.Color(69, 35, 35));
        btnInformeMesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInformeMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnInformeMesa.setText("Mesa Electoral");
        btnInformeMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeMesaActionPerformed(evt);
            }
        });

        btnInformeEleccion.setBackground(new java.awt.Color(69, 35, 35));
        btnInformeEleccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInformeEleccion.setForeground(new java.awt.Color(255, 255, 255));
        btnInformeEleccion.setText("Elección");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInformeMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInformeEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnInformeEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnInformeMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informe detallado", jPanel11);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(140, 43, 43));

        jLabel1.setBackground(new java.awt.Color(140, 43, 43));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Conteo de Votos");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEleccionActionPerformed
        // TODO add your handling code here:
        GestionarEleccionIU GE = new GestionarEleccionIU(elecciones);
        GE.setVisible(true);              
        GE.setLocationRelativeTo(null);   
        GE.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);         
    }//GEN-LAST:event_btnGestionarEleccionActionPerformed

    private void btnRegistrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCandidatoActionPerformed

    }//GEN-LAST:event_btnRegistrarCandidatoActionPerformed

    private void btnGestionarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCandidatoActionPerformed
        // TODO add your handling code here:
         if (partidos.getPartidos().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No hay partidos registrados aún. Registra al menos uno para continuar.",
                "Información", JOptionPane.INFORMATION_MESSAGE);

            GestionarPartidos_IU gp = new GestionarPartidos_IU(partidos);
            gp.setVisible(true);
            gp.setLocationRelativeTo(null);
            gp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }else if(elecciones.getElecciones().isEmpty()){
           JOptionPane.showMessageDialog(this,
                "No hay elecciones registradas aún. Registra al menos uno para continuar.",
                "Información", JOptionPane.INFORMATION_MESSAGE);

            GestionarEleccionIU ge = new GestionarEleccionIU(elecciones);
            ge.setVisible(true);
            ge.setLocationRelativeTo(null);
            ge.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);            
            
        }else {
            GestionarCandidatosIU gc = new GestionarCandidatosIU(candidatos, partidos, elecciones);
            gc.setVisible(true);
            gc.setLocationRelativeTo(null);
            gc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_btnGestionarCandidatoActionPerformed

    private void btnListarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPartidoActionPerformed
        // TODO add your handling code here:
        ListaPartidos_IU LF = new ListaPartidos_IU(partidos);
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        LF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }//GEN-LAST:event_btnListarPartidoActionPerformed

    private void btnGestionarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMesasActionPerformed
        // TODO add your handling code here:
        if(elecciones.getElecciones().isEmpty()){
           JOptionPane.showMessageDialog(this,
                "No hay elecciones registradas aún. Registra al menos uno para continuar.",
                "Información", JOptionPane.INFORMATION_MESSAGE);

            GestionarEleccionIU ge = new GestionarEleccionIU(elecciones);
            ge.setVisible(true);
            ge.setLocationRelativeTo(null);
            ge.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);            
            
        }else {
            GestionarMesasIU gc = new GestionarMesasIU(mesas, elecciones);
            gc.setVisible(true);
            gc.setLocationRelativeTo(null);
            gc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }        
    }//GEN-LAST:event_btnGestionarMesasActionPerformed

    private void btnGestionarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMiembroActionPerformed
        // TODO add your handling code here:
        if (mesas.getMesas().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No hay mesas registradas aún. Registra al menos una para continuar.",
                "Información", JOptionPane.INFORMATION_MESSAGE);

            GestionarMesasIU gp = new GestionarMesasIU(mesas, elecciones);
            gp.setVisible(true);
            gp.setLocationRelativeTo(null);
            gp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }else if(elecciones.getElecciones().isEmpty()){
           JOptionPane.showMessageDialog(this,
                "No hay elecciones registradas aún. Registra al menos uno para continuar.",
                "Información", JOptionPane.INFORMATION_MESSAGE);

            GestionarEleccionIU ge = new GestionarEleccionIU(elecciones);
            ge.setVisible(true);
            ge.setLocationRelativeTo(null);
            ge.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);            
            
        }else {
            GestionarMiembrosIU gc = new GestionarMiembrosIU(miembros, elecciones, mesas);
            gc.setVisible(true);
            gc.setLocationRelativeTo(null);
            gc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }        
        
    }//GEN-LAST:event_btnGestionarMiembroActionPerformed

    private void btnGestionarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarActaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarActaActionPerformed

    private void btnGestionarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPartidoActionPerformed
        // TODO add your handling code here:
        GestionarPartidos_IU ventana = new GestionarPartidos_IU(partidos);
        ventana.setVisible(true);              
        ventana.setLocationRelativeTo(null);   
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        
        
        
    }//GEN-LAST:event_btnGestionarPartidoActionPerformed

    private void btnVisualizarMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarMiembrosActionPerformed
        // TODO add your handling code here:
        ListaMiembrosIU LM = new ListaMiembrosIU(miembros);
        LM.setVisible(true);
        LM.setLocationRelativeTo(null);
        LM.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_btnVisualizarMiembrosActionPerformed

    private void btnInformeMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformeMesaActionPerformed

    private void btnVisualizarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarCandidatosActionPerformed
        // TODO add your handling code here:
        ListaCandidatosIU LC = new ListaCandidatosIU(candidatos);
        LC.setVisible(true);
        LC.setLocationRelativeTo(null);
        LC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
    }//GEN-LAST:event_btnVisualizarCandidatosActionPerformed

    private void btnVisualizarEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarEleccionesActionPerformed
        ListaEleccionesIU LE = new ListaEleccionesIU(elecciones);
        LE.setVisible(true);
        LE.setLocationRelativeTo(null);
        LE.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualizarEleccionesActionPerformed

    private void btnVisualizarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarMesasActionPerformed
        // TODO add your handling code here:
        ListaMesasIU LF = new ListaMesasIU(mesas);
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        LF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
    }//GEN-LAST:event_btnVisualizarMesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarActa;
    private javax.swing.JButton btnBuscarCandidato;
    private javax.swing.JButton btnBuscarEleccion;
    private javax.swing.JButton btnBuscarMesa;
    private javax.swing.JButton btnBuscarMiembro;
    private javax.swing.JButton btnEliminarActa;
    private javax.swing.JButton btnEliminarCandidato;
    private javax.swing.JButton btnEliminarEleccion2;
    private javax.swing.JButton btnEliminarEleccion3;
    private javax.swing.JButton btnEliminarEleccion4;
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JButton btnEliminarMiembro;
    private javax.swing.JButton btnGestionarActa;
    private javax.swing.JButton btnGestionarCandidato;
    private javax.swing.JButton btnGestionarEleccion;
    private javax.swing.JButton btnGestionarMesas;
    private javax.swing.JButton btnGestionarMiembro;
    private javax.swing.JButton btnGestionarPartido;
    private javax.swing.JButton btnInformeEleccion;
    private javax.swing.JButton btnInformeMesa;
    private javax.swing.JButton btnListarPartido;
    private javax.swing.JButton btnModificarActa;
    private javax.swing.JButton btnModificarCandidato;
    private javax.swing.JButton btnModificarEleccion;
    private javax.swing.JButton btnModificarMesa;
    private javax.swing.JButton btnModificarMiembro;
    private javax.swing.JButton btnRegistrarActa;
    private javax.swing.JButton btnRegistrarCandidato;
    private javax.swing.JButton btnRegistrarMesa;
    private javax.swing.JButton btnRegistrarMiembro;
    private javax.swing.JButton btnVisualizarActas;
    private javax.swing.JButton btnVisualizarCandidatos;
    private javax.swing.JButton btnVisualizarElecciones;
    private javax.swing.JButton btnVisualizarMesas;
    private javax.swing.JButton btnVisualizarMiembros;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tablaInforme;
    // End of variables declaration//GEN-END:variables
}
